# Site settings
email: jess.astbury@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Jess Astbury
description: Full-Stack Developer
url: "JAstbury.github.io"
twitter_username: jess_astbury
default_img:

# Profile settings
name: Jess Astbury
profile_img: "/assets/images/jessa.jpg"
profile: Jess Astbury<br/><br/>- english literature geek turned software developer.
social:
  github: JAstbury
  twitter: jess_astbury
  linkedin: jess-astbury-2bb91160



# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
